/* Generated by re2c 0.13.5 on Thu Dec 12 14:54:50 2013 */
#line 1 "yylex.re"
/* -*- mode: c -*- */
/* Given to re2c to generate the lexer `yylex'.
 *
 * Based on c.re in the exmaples distributed with re2c.
 */
#include <string.h>
#include "cast.h"

/*
 * -------------------------------------------------------------------
 *                               Helpers
 * -------------------------------------------------------------------
 */

#define new_func(Foo)                                       \
VALUE cast_new_##Foo##_at(long pos) {                       \
  VALUE c##Foo;                                             \
  c##Foo = rb_const_get(cast_mC, rb_intern(#Foo));          \
  return rb_funcall2(c##Foo, rb_intern("new"), 0, NULL);    \
}
#define set_func(Foo, field)                                    \
VALUE cast_##Foo##_set_##field(VALUE self, VALUE value) {       \
  return rb_funcall2(self, rb_intern(#field "="), 1, &value);   \
}

new_func(IntLiteral);
set_func(IntLiteral, format);
set_func(IntLiteral, val);
set_func(IntLiteral, suffix);

new_func(FloatLiteral);
set_func(FloatLiteral, format);
set_func(FloatLiteral, val);
set_func(FloatLiteral, suffix);

new_func(CharLiteral);
set_func(CharLiteral, prefix);
set_func(CharLiteral, val);

new_func(StringLiteral);
set_func(StringLiteral, prefix);
set_func(StringLiteral, val);

/*
 * -------------------------------------------------------------------
 *                                yylex
 * -------------------------------------------------------------------
 */
#define BSIZE     8192

#define YYLTYPE VALUE

#define YYCTYPE   char
#define YYCURSOR  cursor
#define YYLIMIT   p->lim
#define YYMARKER  p->ptr
#define YYFILL(n) {}

#define RET(sym)      {p->cur = cursor; rb_ary_store(p->token, 0, sym); rb_ary_store(p->token, 1, sym  ); return;}
#define RETVALUE(sym) {p->cur = cursor; rb_ary_store(p->token, 0, sym); rb_ary_store(p->token, 1, value); return;}

/* Raise a ParseError.  `s' is the format string for the exception
 * message, which must contain exactly one '%s', which is replaced by
 * the string delimited by `b' and `e'.
 */
static void error1(char *s, char *b, char *e) {
  char *str;
  str = ALLOCA_N(char, e - b + 1);
  memcpy(str, b, e-b);
  str[e-b] = '\0';
  rb_raise(cast_eParseError, s, str);
}

/* `token' is assumed to be a two element array, which is filled in.
 */
void yylex(VALUE self, cast_Parser *p) {
  char *cursor = p->cur;
  char *cp;
  VALUE value;
 std:
  p->tok = cursor;
  #line 95 "yylex.re"

  
#line 88 "<stdout>"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;

	if ((YYLIMIT - YYCURSOR) < 11) YYFILL(11);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy76;
	case '\t':
	case '\v':
	case '\f':
	case ' ':	goto yy74;
	case '\n':	goto yy78;
	case '!':	goto yy50;
	case '"':	goto yy29;
	case '%':	goto yy40;
	case '&':	goto yy42;
	case '\'':	goto yy27;
	case '(':	goto yy62;
	case ')':	goto yy64;
	case '*':	goto yy38;
	case '+':	goto yy34;
	case ',':	goto yy58;
	case '-':	goto yy36;
	case '.':	goto yy25;
	case '/':	goto yy2;
	case '0':	goto yy22;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy24;
	case ':':	goto yy60;
	case ';':	goto yy52;
	case '<':	goto yy32;
	case '=':	goto yy48;
	case '>':	goto yy30;
	case '?':	goto yy72;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'h':
	case 'j':
	case 'k':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'x':
	case 'y':
	case 'z':	goto yy21;
	case '[':	goto yy66;
	case ']':	goto yy68;
	case '^':	goto yy44;
	case '_':	goto yy20;
	case 'a':	goto yy4;
	case 'b':	goto yy6;
	case 'c':	goto yy7;
	case 'd':	goto yy8;
	case 'e':	goto yy9;
	case 'f':	goto yy10;
	case 'g':	goto yy11;
	case 'i':	goto yy12;
	case 'l':	goto yy13;
	case 'r':	goto yy14;
	case 's':	goto yy15;
	case 't':	goto yy16;
	case 'u':	goto yy17;
	case 'v':	goto yy18;
	case 'w':	goto yy19;
	case '{':	goto yy54;
	case '|':	goto yy46;
	case '}':	goto yy56;
	case '~':	goto yy70;
	default:	goto yy80;
	}
yy2:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '*':	goto yy443;
	case '/':	goto yy441;
	case '=':	goto yy439;
	default:	goto yy3;
	}
yy3:
#line 264 "yylex.re"
	{ RET(cast_sym_DIV); }
#line 204 "<stdout>"
yy4:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy243;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	case 'u':	goto yy435;
	default:	goto yy5;
	}
yy5:
#line 138 "yylex.re"
	{
        value = rb_str_new(p->tok, cursor - p->tok);
        if (rb_funcall2(rb_funcall2(self, rb_intern("type_names"), 0, NULL),
                       rb_intern("include?"), 1, &value) == Qtrue) {
          RETVALUE(cast_sym_TYPENAME);
        } else {
          RETVALUE(cast_sym_ID);
        }
    }
#line 287 "<stdout>"
yy6:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy243;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	case 'r':	goto yy430;
	default:	goto yy5;
	}
yy7:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy243;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	case 'a':	goto yy411;
	case 'h':	goto yy412;
	case 'o':	goto yy413;
	default:	goto yy5;
	}
yy8:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy243;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	case 'e':	goto yy397;
	case 'o':	goto yy398;
	default:	goto yy5;
	}
yy9:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy243;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'm':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'y':
	case 'z':	goto yy244;
	case 'l':	goto yy383;
	case 'n':	goto yy384;
	case 'x':	goto yy385;
	default:	goto yy5;
	}
yy10:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy243;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'm':
	case 'n':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	case 'l':	goto yy375;
	case 'o':	goto yy376;
	default:	goto yy5;
	}
yy11:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy243;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	case 'o':	goto yy371;
	default:	goto yy5;
	}
yy12:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy243;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	case 'f':	goto yy361;
	case 'n':	goto yy363;
	default:	goto yy5;
	}
yy13:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy243;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	case 'o':	goto yy357;
	default:	goto yy5;
	}
yy14:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy243;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	case 'e':	goto yy337;
	default:	goto yy5;
	}
yy15:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy243;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 'u':
	case 'v':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	case 'h':	goto yy304;
	case 'i':	goto yy305;
	case 't':	goto yy306;
	case 'w':	goto yy307;
	default:	goto yy5;
	}
yy16:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy243;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'z':	goto yy244;
	case 'y':	goto yy297;
	default:	goto yy5;
	}
yy17:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy243;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	case 'n':	goto yy285;
	default:	goto yy5;
	}
yy18:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy243;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	case 'o':	goto yy274;
	default:	goto yy5;
	}
yy19:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy243;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	case 'h':	goto yy269;
	default:	goto yy5;
	}
yy20:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy243;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	case 'B':	goto yy246;
	case 'C':	goto yy247;
	case 'I':	goto yy248;
	default:	goto yy5;
	}
yy21:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy243;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy5;
	}
yy22:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '.':	goto yy163;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy188;
	case 'B':
	case 'b':	goto yy191;
	case 'E':
	case 'e':	goto yy166;
	case 'L':	goto yy168;
	case 'U':
	case 'u':	goto yy167;
	case 'X':
	case 'x':	goto yy187;
	case 'l':	goto yy169;
	default:	goto yy23;
	}
yy23:
#line 176 "yylex.re"
	{
        value = cast_new_IntLiteral_at(p->lineno);
        cast_IntLiteral_set_format(value, ID2SYM(rb_intern("dec")));
        cast_IntLiteral_set_val(value, LONG2NUM(strtol(p->tok, (char **)&cp, 10)));
        if (cp < cursor)
            cast_IntLiteral_set_suffix(value, rb_str_new(cp, cursor - cp));
        RETVALUE(cast_sym_ICON);
    }
#line 1461 "<stdout>"
yy24:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy165;
yy25:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '.':	goto yy152;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy153;
	default:	goto yy26;
	}
yy26:
#line 257 "yylex.re"
	{ RET(cast_sym_DOT); }
#line 1486 "<stdout>"
yy27:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\'':	goto yy28;
	default:	goto yy143;
	}
yy28:
#line 292 "yylex.re"
	{
            rb_raise(cast_eParseError, "%ld: unexpected character: %c (ASCII %d)\n", p->lineno, *p->tok, (int)*p->tok);
            goto std;
        }
#line 1500 "<stdout>"
yy29:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy132;
yy30:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy125;
	case '>':	goto yy127;
	default:	goto yy31;
	}
yy31:
#line 267 "yylex.re"
	{ RET(cast_sym_GT); }
#line 1515 "<stdout>"
yy32:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '%':	goto yy115;
	case ':':	goto yy117;
	case '<':	goto yy121;
	case '=':	goto yy119;
	default:	goto yy33;
	}
yy33:
#line 266 "yylex.re"
	{ RET(cast_sym_LT); }
#line 1528 "<stdout>"
yy34:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '+':	goto yy111;
	case '=':	goto yy113;
	default:	goto yy35;
	}
yy35:
#line 262 "yylex.re"
	{ RET(cast_sym_ADD); }
#line 1539 "<stdout>"
yy36:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '-':	goto yy107;
	case '=':	goto yy109;
	case '>':	goto yy105;
	default:	goto yy37;
	}
yy37:
#line 261 "yylex.re"
	{ RET(cast_sym_SUB); }
#line 1551 "<stdout>"
yy38:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy103;
	default:	goto yy39;
	}
yy39:
#line 263 "yylex.re"
	{ RET(cast_sym_MUL); }
#line 1561 "<stdout>"
yy40:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy101;
	case '>':	goto yy99;
	default:	goto yy41;
	}
yy41:
#line 265 "yylex.re"
	{ RET(cast_sym_MOD); }
#line 1572 "<stdout>"
yy42:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '&':	goto yy95;
	case '=':	goto yy97;
	default:	goto yy43;
	}
yy43:
#line 258 "yylex.re"
	{ RET(cast_sym_AND); }
#line 1583 "<stdout>"
yy44:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy93;
	default:	goto yy45;
	}
yy45:
#line 268 "yylex.re"
	{ RET(cast_sym_XOR); }
#line 1593 "<stdout>"
yy46:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy91;
	case '|':	goto yy89;
	default:	goto yy47;
	}
yy47:
#line 269 "yylex.re"
	{ RET(cast_sym_OR); }
#line 1604 "<stdout>"
yy48:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy87;
	default:	goto yy49;
	}
yy49:
#line 252 "yylex.re"
	{ RET(cast_sym_EQ); }
#line 1614 "<stdout>"
yy50:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy85;
	default:	goto yy51;
	}
yy51:
#line 259 "yylex.re"
	{ RET(cast_sym_BANG); }
#line 1624 "<stdout>"
yy52:
	++YYCURSOR;
#line 247 "yylex.re"
	{ RET(cast_sym_SEMICOLON); }
#line 1629 "<stdout>"
yy54:
	++YYCURSOR;
#line 248 "yylex.re"
	{ RET(cast_sym_LBRACE); }
#line 1634 "<stdout>"
yy56:
	++YYCURSOR;
#line 249 "yylex.re"
	{ RET(cast_sym_RBRACE); }
#line 1639 "<stdout>"
yy58:
	++YYCURSOR;
#line 250 "yylex.re"
	{ RET(cast_sym_COMMA); }
#line 1644 "<stdout>"
yy60:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '>':	goto yy83;
	default:	goto yy61;
	}
yy61:
#line 251 "yylex.re"
	{ RET(cast_sym_COLON); }
#line 1654 "<stdout>"
yy62:
	++YYCURSOR;
#line 253 "yylex.re"
	{ RET(cast_sym_LPAREN); }
#line 1659 "<stdout>"
yy64:
	++YYCURSOR;
#line 254 "yylex.re"
	{ RET(cast_sym_RPAREN); }
#line 1664 "<stdout>"
yy66:
	++YYCURSOR;
#line 255 "yylex.re"
	{ RET(cast_sym_LBRACKET); }
#line 1669 "<stdout>"
yy68:
	++YYCURSOR;
#line 256 "yylex.re"
	{ RET(cast_sym_RBRACKET); }
#line 1674 "<stdout>"
yy70:
	++YYCURSOR;
#line 260 "yylex.re"
	{ RET(cast_sym_NOT); }
#line 1679 "<stdout>"
yy72:
	++YYCURSOR;
#line 270 "yylex.re"
	{ RET(cast_sym_QUESTION); }
#line 1684 "<stdout>"
yy74:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy82;
yy75:
#line 277 "yylex.re"
	{ goto std; }
#line 1692 "<stdout>"
yy76:
	++YYCURSOR;
#line 280 "yylex.re"
	{
            if(cursor == p->eof) RET(Qnil);
            goto std;
        }
#line 1700 "<stdout>"
yy78:
	++YYCURSOR;
#line 286 "yylex.re"
	{
            p->pos = cursor; ++p->lineno;
            goto std;
        }
#line 1708 "<stdout>"
yy80:
	yych = *++YYCURSOR;
	goto yy28;
yy81:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy82:
	switch (yych) {
	case '\t':
	case '\v':
	case '\f':
	case ' ':	goto yy81;
	default:	goto yy75;
	}
yy83:
	++YYCURSOR;
#line 274 "yylex.re"
	{ RET(cast_sym_RBRACKET); }
#line 1728 "<stdout>"
yy85:
	++YYCURSOR;
#line 246 "yylex.re"
	{ RET(cast_sym_NEQ); }
#line 1733 "<stdout>"
yy87:
	++YYCURSOR;
#line 245 "yylex.re"
	{ RET(cast_sym_EQEQ); }
#line 1738 "<stdout>"
yy89:
	++YYCURSOR;
#line 242 "yylex.re"
	{ RET(cast_sym_OROR); }
#line 1743 "<stdout>"
yy91:
	++YYCURSOR;
#line 235 "yylex.re"
	{ RET(cast_sym_OREQ); }
#line 1748 "<stdout>"
yy93:
	++YYCURSOR;
#line 234 "yylex.re"
	{ RET(cast_sym_XOREQ); }
#line 1753 "<stdout>"
yy95:
	++YYCURSOR;
#line 241 "yylex.re"
	{ RET(cast_sym_ANDAND); }
#line 1758 "<stdout>"
yy97:
	++YYCURSOR;
#line 233 "yylex.re"
	{ RET(cast_sym_ANDEQ); }
#line 1763 "<stdout>"
yy99:
	++YYCURSOR;
#line 275 "yylex.re"
	{ RET(cast_sym_RBRACE); }
#line 1768 "<stdout>"
yy101:
	++YYCURSOR;
#line 232 "yylex.re"
	{ RET(cast_sym_MODEQ); }
#line 1773 "<stdout>"
yy103:
	++YYCURSOR;
#line 230 "yylex.re"
	{ RET(cast_sym_MULEQ); }
#line 1778 "<stdout>"
yy105:
	++YYCURSOR;
#line 240 "yylex.re"
	{ RET(cast_sym_ARROW); }
#line 1783 "<stdout>"
yy107:
	++YYCURSOR;
#line 239 "yylex.re"
	{ RET(cast_sym_DEC); }
#line 1788 "<stdout>"
yy109:
	++YYCURSOR;
#line 229 "yylex.re"
	{ RET(cast_sym_SUBEQ); }
#line 1793 "<stdout>"
yy111:
	++YYCURSOR;
#line 238 "yylex.re"
	{ RET(cast_sym_INC); }
#line 1798 "<stdout>"
yy113:
	++YYCURSOR;
#line 228 "yylex.re"
	{ RET(cast_sym_ADDEQ); }
#line 1803 "<stdout>"
yy115:
	++YYCURSOR;
#line 273 "yylex.re"
	{ RET(cast_sym_LBRACE); }
#line 1808 "<stdout>"
yy117:
	++YYCURSOR;
#line 272 "yylex.re"
	{ RET(cast_sym_LBRACKET); }
#line 1813 "<stdout>"
yy119:
	++YYCURSOR;
#line 243 "yylex.re"
	{ RET(cast_sym_LEQ); }
#line 1818 "<stdout>"
yy121:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy123;
	default:	goto yy122;
	}
yy122:
#line 237 "yylex.re"
	{ RET(cast_sym_LSHIFT); }
#line 1828 "<stdout>"
yy123:
	++YYCURSOR;
#line 227 "yylex.re"
	{ RET(cast_sym_LSHIFTEQ); }
#line 1833 "<stdout>"
yy125:
	++YYCURSOR;
#line 244 "yylex.re"
	{ RET(cast_sym_GEQ); }
#line 1838 "<stdout>"
yy127:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy129;
	default:	goto yy128;
	}
yy128:
#line 236 "yylex.re"
	{ RET(cast_sym_RSHIFT); }
#line 1848 "<stdout>"
yy129:
	++YYCURSOR;
#line 226 "yylex.re"
	{ RET(cast_sym_RSHIFTEQ); }
#line 1853 "<stdout>"
yy131:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy132:
	switch (yych) {
	case '"':	goto yy135;
	case '\\':	goto yy133;
	default:	goto yy131;
	}
yy133:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '"':
	case '\'':
	case '?':
	case '\\':
	case 'a':
	case 'b':
	case 'f':
	case 'n':
	case 'r':
	case 't':
	case 'v':	goto yy131;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy137;
	case 'x':	goto yy138;
	default:	goto yy134;
	}
yy134:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy5;
	case 1: 	goto yy23;
	case 2: 	goto yy26;
	case 3: 	goto yy28;
	case 4: 	goto yy155;
	case 5: 	goto yy190;
	case 6: 	goto yy211;
	case 7: 	goto yy215;
	}
yy135:
	++YYCURSOR;
#line 213 "yylex.re"
	{
        value = cast_new_StringLiteral_at(p->lineno);
        if (p->tok[0] == '"') {
            cp = p->tok;
        } else {
            cast_StringLiteral_set_prefix(value, rb_str_new(p->tok, 1));
            cp = p->tok + 1;
        }
        cast_StringLiteral_set_val(value, rb_str_new(cp + 1, cursor - cp - 2));
        RETVALUE(cast_sym_SCON);
    }
#line 1917 "<stdout>"
yy137:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '"':	goto yy135;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy141;
	case '\\':	goto yy133;
	default:	goto yy131;
	}
yy138:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy139;
	default:	goto yy134;
	}
yy139:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '"':	goto yy135;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy139;
	case '\\':	goto yy133;
	default:	goto yy131;
	}
yy141:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '"':	goto yy135;
	case '\\':	goto yy133;
	default:	goto yy131;
	}
yy142:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy143:
	switch (yych) {
	case '\'':	goto yy149;
	case '\\':	goto yy144;
	default:	goto yy142;
	}
yy144:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '"':
	case '\'':
	case '?':
	case '\\':
	case 'a':
	case 'b':
	case 'f':
	case 'n':
	case 'r':
	case 't':
	case 'v':	goto yy142;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy145;
	case 'x':	goto yy146;
	default:	goto yy134;
	}
yy145:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\'':	goto yy149;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy151;
	case '\\':	goto yy144;
	default:	goto yy142;
	}
yy146:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy147;
	default:	goto yy134;
	}
yy147:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\'':	goto yy149;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy147;
	case '\\':	goto yy144;
	default:	goto yy142;
	}
yy149:
	++YYCURSOR;
#line 202 "yylex.re"
	{
        value = cast_new_CharLiteral_at(p->lineno);
        if (p->tok[0] == '\'') {
            cp = p->tok;
        } else {
            cast_CharLiteral_set_prefix(value, rb_str_new(p->tok, 1));
            cp = p->tok + 1;
        }
        cast_CharLiteral_set_val(value, rb_str_new(cp + 1, cursor - cp - 2));
        RETVALUE(cast_sym_CCON);
    }
#line 2132 "<stdout>"
yy151:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\'':	goto yy149;
	case '\\':	goto yy144;
	default:	goto yy142;
	}
yy152:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy161;
	default:	goto yy134;
	}
yy153:
	yyaccept = 4;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy153;
	case 'E':
	case 'e':	goto yy156;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy157;
	default:	goto yy155;
	}
yy155:
#line 185 "yylex.re"
	{
        value = cast_new_FloatLiteral_at(p->lineno);
        cast_FloatLiteral_set_format(value, ID2SYM(rb_intern("dec")));
        cast_FloatLiteral_set_val(value, rb_float_new(strtod(p->tok, (char **)&cp)));
        if (cp < cursor)
            cast_FloatLiteral_set_suffix(value, rb_str_new(cp, cursor - cp));
        RETVALUE(cast_sym_FCON);
    }
#line 2182 "<stdout>"
yy156:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy158;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy159;
	default:	goto yy134;
	}
yy157:
	yych = *++YYCURSOR;
	goto yy155;
yy158:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy159;
	default:	goto yy134;
	}
yy159:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy159;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy157;
	default:	goto yy155;
	}
yy161:
	++YYCURSOR;
#line 225 "yylex.re"
	{ RET(cast_sym_ELLIPSIS); }
#line 2243 "<stdout>"
yy163:
	yyaccept = 4;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'E':
	case 'e':	goto yy179;
	default:	goto yy178;
	}
yy164:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
yy165:
	switch (yych) {
	case '.':	goto yy163;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy164;
	case 'E':
	case 'e':	goto yy166;
	case 'L':	goto yy168;
	case 'U':
	case 'u':	goto yy167;
	case 'l':	goto yy169;
	default:	goto yy23;
	}
yy166:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy174;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy175;
	default:	goto yy134;
	}
yy167:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':	goto yy172;
	case 'l':	goto yy173;
	default:	goto yy23;
	}
yy168:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':	goto yy170;
	case 'U':
	case 'u':	goto yy171;
	default:	goto yy23;
	}
yy169:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy171;
	case 'l':	goto yy170;
	default:	goto yy23;
	}
yy170:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy171;
	default:	goto yy23;
	}
yy171:
	yych = *++YYCURSOR;
	goto yy23;
yy172:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':	goto yy171;
	default:	goto yy23;
	}
yy173:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy171;
	default:	goto yy23;
	}
yy174:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy175;
	default:	goto yy134;
	}
yy175:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy175;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy157;
	default:	goto yy155;
	}
yy177:
	yyaccept = 4;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
yy178:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy177;
	case 'E':
	case 'e':	goto yy183;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy157;
	default:	goto yy155;
	}
yy179:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy180;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy181;
	default:	goto yy134;
	}
yy180:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy181;
	default:	goto yy134;
	}
yy181:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy181;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy157;
	default:	goto yy155;
	}
yy183:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy184;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy185;
	default:	goto yy134;
	}
yy184:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy185;
	default:	goto yy134;
	}
yy185:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy185;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy157;
	default:	goto yy155;
	}
yy187:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy212;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy209;
	default:	goto yy134;
	}
yy188:
	yyaccept = 5;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
	switch (yych) {
	case '.':	goto yy163;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy188;
	case 'E':
	case 'e':	goto yy166;
	case 'L':	goto yy203;
	case 'U':
	case 'u':	goto yy202;
	case 'l':	goto yy204;
	default:	goto yy190;
	}
yy190:
#line 156 "yylex.re"
	{
        value = cast_new_IntLiteral_at(p->lineno);
        cast_IntLiteral_set_format(value, ID2SYM(rb_intern("oct")));
        cast_IntLiteral_set_val(value, LONG2NUM(strtol(p->tok, (char **)&cp, 8)));
        if (cp < cursor) {
            if (cp[0] == '8' || cp[0] == '9')
                rb_raise(cast_eParseError, "bad octal digit: %c", cp[0]);
            cast_IntLiteral_set_suffix(value, rb_str_new(cp, cursor - cp));
        }
        RETVALUE(cast_sym_ICON);
    }
#line 2573 "<stdout>"
yy191:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':	goto yy192;
	default:	goto yy134;
	}
yy192:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':	goto yy192;
	case 'L':	goto yy196;
	case 'U':
	case 'u':	goto yy195;
	case 'l':	goto yy197;
	default:	goto yy194;
	}
yy194:
#line 167 "yylex.re"
	{
        value = cast_new_IntLiteral_at(p->lineno);
        cast_IntLiteral_set_format(value, ID2SYM(rb_intern("bin")));
        cast_IntLiteral_set_val(value, LONG2NUM(strtol(p->tok, (char **)&cp, 2)));
        if (cp < cursor)
            cast_IntLiteral_set_suffix(value, rb_str_new(cp, cursor - cp));
        RETVALUE(cast_sym_ICON);
    }
#line 2604 "<stdout>"
yy195:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':	goto yy200;
	case 'l':	goto yy201;
	default:	goto yy194;
	}
yy196:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':	goto yy198;
	case 'U':
	case 'u':	goto yy199;
	default:	goto yy194;
	}
yy197:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy199;
	case 'l':	goto yy198;
	default:	goto yy194;
	}
yy198:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy199;
	default:	goto yy194;
	}
yy199:
	yych = *++YYCURSOR;
	goto yy194;
yy200:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':	goto yy199;
	default:	goto yy194;
	}
yy201:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy199;
	default:	goto yy194;
	}
yy202:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':	goto yy207;
	case 'l':	goto yy208;
	default:	goto yy190;
	}
yy203:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':	goto yy205;
	case 'U':
	case 'u':	goto yy206;
	default:	goto yy190;
	}
yy204:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy206;
	case 'l':	goto yy205;
	default:	goto yy190;
	}
yy205:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy206;
	default:	goto yy190;
	}
yy206:
	yych = *++YYCURSOR;
	goto yy190;
yy207:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':	goto yy206;
	default:	goto yy190;
	}
yy208:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy206;
	default:	goto yy190;
	}
yy209:
	yyaccept = 6;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
	switch (yych) {
	case '.':	goto yy221;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy209;
	case 'L':	goto yy224;
	case 'P':
	case 'p':	goto yy222;
	case 'U':
	case 'u':	goto yy223;
	case 'l':	goto yy225;
	default:	goto yy211;
	}
yy211:
#line 148 "yylex.re"
	{
        value = cast_new_IntLiteral_at(p->lineno);
        cast_IntLiteral_set_format(value, ID2SYM(rb_intern("hex")));
        cast_IntLiteral_set_val(value, LONG2NUM(strtol(p->tok, (char **)&cp, 16)));
        if (cp < cursor)
            cast_IntLiteral_set_suffix(value, rb_str_new(cp, cursor - cp));
        RETVALUE(cast_sym_ICON);
    }
#line 2742 "<stdout>"
yy212:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy213;
	default:	goto yy134;
	}
yy213:
	yyaccept = 7;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy213;
	case 'L':
	case 'l':	goto yy217;
	case 'P':
	case 'p':	goto yy216;
	default:	goto yy215;
	}
yy215:
#line 193 "yylex.re"
	{
        value = cast_new_FloatLiteral_at(p->lineno);
        cast_FloatLiteral_set_format(value, ID2SYM(rb_intern("hex")));
        cast_FloatLiteral_set_val(value, rb_float_new(strtod(p->tok, (char **)&cp)));
        if (cp < cursor)
            cast_FloatLiteral_set_suffix(value, rb_str_new(cp, cursor - cp));
        RETVALUE(cast_sym_FCON);
    }
#line 2814 "<stdout>"
yy216:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy218;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy219;
	default:	goto yy134;
	}
yy217:
	yych = *++YYCURSOR;
	goto yy215;
yy218:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy219;
	default:	goto yy134;
	}
yy219:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy219;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy217;
	default:	goto yy215;
	}
yy221:
	yyaccept = 7;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'P':
	case 'p':	goto yy235;
	default:	goto yy234;
	}
yy222:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy230;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy231;
	default:	goto yy134;
	}
yy223:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':	goto yy228;
	case 'l':	goto yy229;
	default:	goto yy211;
	}
yy224:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':	goto yy226;
	case 'U':
	case 'u':	goto yy227;
	default:	goto yy211;
	}
yy225:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy227;
	case 'l':	goto yy226;
	default:	goto yy211;
	}
yy226:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy227;
	default:	goto yy211;
	}
yy227:
	yych = *++YYCURSOR;
	goto yy211;
yy228:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':	goto yy227;
	default:	goto yy211;
	}
yy229:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy227;
	default:	goto yy211;
	}
yy230:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy231;
	default:	goto yy134;
	}
yy231:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy231;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy217;
	default:	goto yy215;
	}
yy233:
	yyaccept = 7;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
yy234:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy233;
	case 'L':
	case 'l':	goto yy217;
	case 'P':
	case 'p':	goto yy239;
	default:	goto yy215;
	}
yy235:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy236;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy237;
	default:	goto yy134;
	}
yy236:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy237;
	default:	goto yy134;
	}
yy237:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy237;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy217;
	default:	goto yy215;
	}
yy239:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy240;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy241;
	default:	goto yy134;
	}
yy240:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy241;
	default:	goto yy134;
	}
yy241:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy241;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy217;
	default:	goto yy215;
	}
yy243:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\'':	goto yy134;
	default:	goto yy143;
	}
yy244:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy245:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy5;
	}
yy246:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy265;
	default:	goto yy245;
	}
yy247:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy258;
	default:	goto yy245;
	}
yy248:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy249;
	default:	goto yy245;
	}
yy249:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy250;
	default:	goto yy245;
	}
yy250:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy251;
	default:	goto yy245;
	}
yy251:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy252;
	default:	goto yy245;
	}
yy252:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy253;
	default:	goto yy245;
	}
yy253:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy254;
	default:	goto yy245;
	}
yy254:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy255;
	default:	goto yy245;
	}
yy255:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'y':	goto yy256;
	default:	goto yy245;
	}
yy256:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy257;
	}
yy257:
#line 136 "yylex.re"
	{ RET(cast_sym_IMAGINARY); }
#line 3326 "<stdout>"
yy258:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy259;
	default:	goto yy245;
	}
yy259:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy260;
	default:	goto yy245;
	}
yy260:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy261;
	default:	goto yy245;
	}
yy261:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy262;
	default:	goto yy245;
	}
yy262:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'x':	goto yy263;
	default:	goto yy245;
	}
yy263:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy264;
	}
yy264:
#line 135 "yylex.re"
	{ RET(cast_sym_COMPLEX); }
#line 3428 "<stdout>"
yy265:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy266;
	default:	goto yy245;
	}
yy266:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy267;
	default:	goto yy245;
	}
yy267:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy268;
	}
yy268:
#line 134 "yylex.re"
	{ RET(cast_sym_BOOL); }
#line 3512 "<stdout>"
yy269:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy270;
	default:	goto yy245;
	}
yy270:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy271;
	default:	goto yy245;
	}
yy271:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy272;
	default:	goto yy245;
	}
yy272:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy273;
	}
yy273:
#line 131 "yylex.re"
	{ RET(cast_sym_WHILE); }
#line 3602 "<stdout>"
yy274:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy275;
	case 'l':	goto yy276;
	default:	goto yy245;
	}
yy275:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy283;
	default:	goto yy245;
	}
yy276:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy277;
	default:	goto yy245;
	}
yy277:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy278;
	default:	goto yy245;
	}
yy278:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy279;
	default:	goto yy245;
	}
yy279:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy280;
	default:	goto yy245;
	}
yy280:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy281;
	default:	goto yy245;
	}
yy281:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy282;
	}
yy282:
#line 130 "yylex.re"
	{ RET(cast_sym_VOLATILE); }
#line 3717 "<stdout>"
yy283:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy284;
	}
yy284:
#line 129 "yylex.re"
	{ RET(cast_sym_VOID); }
#line 3789 "<stdout>"
yy285:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy286;
	case 's':	goto yy287;
	default:	goto yy245;
	}
yy286:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy294;
	default:	goto yy245;
	}
yy287:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy288;
	default:	goto yy245;
	}
yy288:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy289;
	default:	goto yy245;
	}
yy289:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy290;
	default:	goto yy245;
	}
yy290:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy291;
	default:	goto yy245;
	}
yy291:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy292;
	default:	goto yy245;
	}
yy292:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy293;
	}
yy293:
#line 128 "yylex.re"
	{ RET(cast_sym_UNSIGNED); }
#line 3904 "<stdout>"
yy294:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy295;
	default:	goto yy245;
	}
yy295:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy296;
	}
yy296:
#line 127 "yylex.re"
	{ RET(cast_sym_UNION); }
#line 3982 "<stdout>"
yy297:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy298;
	default:	goto yy245;
	}
yy298:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy299;
	default:	goto yy245;
	}
yy299:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy300;
	default:	goto yy245;
	}
yy300:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy301;
	default:	goto yy245;
	}
yy301:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy302;
	default:	goto yy245;
	}
yy302:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy303;
	}
yy303:
#line 126 "yylex.re"
	{ RET(cast_sym_TYPEDEF); }
#line 4084 "<stdout>"
yy304:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy333;
	default:	goto yy245;
	}
yy305:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy323;
	case 'z':	goto yy324;
	default:	goto yy245;
	}
yy306:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy313;
	case 'r':	goto yy314;
	default:	goto yy245;
	}
yy307:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy308;
	default:	goto yy245;
	}
yy308:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy309;
	default:	goto yy245;
	}
yy309:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy310;
	default:	goto yy245;
	}
yy310:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy311;
	default:	goto yy245;
	}
yy311:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy312;
	}
yy312:
#line 125 "yylex.re"
	{ RET(cast_sym_SWITCH); }
#line 4200 "<stdout>"
yy313:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy319;
	default:	goto yy245;
	}
yy314:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy315;
	default:	goto yy245;
	}
yy315:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy316;
	default:	goto yy245;
	}
yy316:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy317;
	default:	goto yy245;
	}
yy317:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy318;
	}
yy318:
#line 124 "yylex.re"
	{ RET(cast_sym_STRUCT); }
#line 4296 "<stdout>"
yy319:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy320;
	default:	goto yy245;
	}
yy320:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy321;
	default:	goto yy245;
	}
yy321:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy322;
	}
yy322:
#line 123 "yylex.re"
	{ RET(cast_sym_STATIC); }
#line 4380 "<stdout>"
yy323:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy329;
	default:	goto yy245;
	}
yy324:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy325;
	default:	goto yy245;
	}
yy325:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy326;
	default:	goto yy245;
	}
yy326:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy327;
	default:	goto yy245;
	}
yy327:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy328;
	}
yy328:
#line 122 "yylex.re"
	{ RET(cast_sym_SIZEOF); }
#line 4476 "<stdout>"
yy329:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy330;
	default:	goto yy245;
	}
yy330:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy331;
	default:	goto yy245;
	}
yy331:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy332;
	}
yy332:
#line 121 "yylex.re"
	{ RET(cast_sym_SIGNED); }
#line 4560 "<stdout>"
yy333:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy334;
	default:	goto yy245;
	}
yy334:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy335;
	default:	goto yy245;
	}
yy335:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy336;
	}
yy336:
#line 120 "yylex.re"
	{ RET(cast_sym_SHORT); }
#line 4644 "<stdout>"
yy337:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy338;
	case 's':	goto yy340;
	case 't':	goto yy339;
	default:	goto yy245;
	}
yy338:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy351;
	default:	goto yy245;
	}
yy339:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy347;
	default:	goto yy245;
	}
yy340:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy341;
	default:	goto yy245;
	}
yy341:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy342;
	default:	goto yy245;
	}
yy342:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy343;
	default:	goto yy245;
	}
yy343:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy344;
	default:	goto yy245;
	}
yy344:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy345;
	default:	goto yy245;
	}
yy345:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy346;
	}
yy346:
#line 133 "yylex.re"
	{ RET(cast_sym_RESTRICT); }
#line 4766 "<stdout>"
yy347:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy348;
	default:	goto yy245;
	}
yy348:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy349;
	default:	goto yy245;
	}
yy349:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy350;
	}
yy350:
#line 119 "yylex.re"
	{ RET(cast_sym_RETURN); }
#line 4850 "<stdout>"
yy351:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy352;
	default:	goto yy245;
	}
yy352:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy353;
	default:	goto yy245;
	}
yy353:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy354;
	default:	goto yy245;
	}
yy354:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy355;
	default:	goto yy245;
	}
yy355:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy356;
	}
yy356:
#line 118 "yylex.re"
	{ RET(cast_sym_REGISTER); }
#line 4946 "<stdout>"
yy357:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy358;
	default:	goto yy245;
	}
yy358:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy359;
	default:	goto yy245;
	}
yy359:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy360;
	}
yy360:
#line 117 "yylex.re"
	{ RET(cast_sym_LONG); }
#line 5030 "<stdout>"
yy361:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy362;
	}
yy362:
#line 115 "yylex.re"
	{ RET(cast_sym_IF); }
#line 5102 "<stdout>"
yy363:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy366;
	case 't':	goto yy364;
	default:	goto yy245;
	}
yy364:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy365;
	}
yy365:
#line 116 "yylex.re"
	{ RET(cast_sym_INT); }
#line 5181 "<stdout>"
yy366:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy367;
	default:	goto yy245;
	}
yy367:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy368;
	default:	goto yy245;
	}
yy368:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy369;
	default:	goto yy245;
	}
yy369:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy370;
	}
yy370:
#line 132 "yylex.re"
	{ RET(cast_sym_INLINE); }
#line 5271 "<stdout>"
yy371:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy372;
	default:	goto yy245;
	}
yy372:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy373;
	default:	goto yy245;
	}
yy373:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy374;
	}
yy374:
#line 114 "yylex.re"
	{ RET(cast_sym_GOTO); }
#line 5355 "<stdout>"
yy375:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy379;
	default:	goto yy245;
	}
yy376:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy377;
	default:	goto yy245;
	}
yy377:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy378;
	}
yy378:
#line 113 "yylex.re"
	{ RET(cast_sym_FOR); }
#line 5439 "<stdout>"
yy379:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy380;
	default:	goto yy245;
	}
yy380:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy381;
	default:	goto yy245;
	}
yy381:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy382;
	}
yy382:
#line 112 "yylex.re"
	{ RET(cast_sym_FLOAT); }
#line 5523 "<stdout>"
yy383:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy394;
	default:	goto yy245;
	}
yy384:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy391;
	default:	goto yy245;
	}
yy385:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy386;
	default:	goto yy245;
	}
yy386:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy387;
	default:	goto yy245;
	}
yy387:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy388;
	default:	goto yy245;
	}
yy388:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy389;
	default:	goto yy245;
	}
yy389:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy390;
	}
yy390:
#line 111 "yylex.re"
	{ RET(cast_sym_EXTERN); }
#line 5631 "<stdout>"
yy391:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy392;
	default:	goto yy245;
	}
yy392:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy393;
	}
yy393:
#line 110 "yylex.re"
	{ RET(cast_sym_ENUM); }
#line 5709 "<stdout>"
yy394:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy395;
	default:	goto yy245;
	}
yy395:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy396;
	}
yy396:
#line 109 "yylex.re"
	{ RET(cast_sym_ELSE); }
#line 5787 "<stdout>"
yy397:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy405;
	default:	goto yy245;
	}
yy398:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	case 'u':	goto yy400;
	default:	goto yy399;
	}
yy399:
#line 107 "yylex.re"
	{ RET(cast_sym_DO); }
#line 5865 "<stdout>"
yy400:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy401;
	default:	goto yy245;
	}
yy401:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy402;
	default:	goto yy245;
	}
yy402:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy403;
	default:	goto yy245;
	}
yy403:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy404;
	}
yy404:
#line 108 "yylex.re"
	{ RET(cast_sym_DOUBLE); }
#line 5955 "<stdout>"
yy405:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy406;
	default:	goto yy245;
	}
yy406:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy407;
	default:	goto yy245;
	}
yy407:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy408;
	default:	goto yy245;
	}
yy408:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy409;
	default:	goto yy245;
	}
yy409:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy410;
	}
yy410:
#line 106 "yylex.re"
	{ RET(cast_sym_DEFAULT); }
#line 6051 "<stdout>"
yy411:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy427;
	default:	goto yy245;
	}
yy412:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy424;
	default:	goto yy245;
	}
yy413:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy414;
	default:	goto yy245;
	}
yy414:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy415;
	case 't':	goto yy416;
	default:	goto yy245;
	}
yy415:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy422;
	default:	goto yy245;
	}
yy416:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy417;
	default:	goto yy245;
	}
yy417:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy418;
	default:	goto yy245;
	}
yy418:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy419;
	default:	goto yy245;
	}
yy419:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy420;
	default:	goto yy245;
	}
yy420:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy421;
	}
yy421:
#line 105 "yylex.re"
	{ RET(cast_sym_CONTINUE); }
#line 6178 "<stdout>"
yy422:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy423;
	}
yy423:
#line 104 "yylex.re"
	{ RET(cast_sym_CONST); }
#line 6250 "<stdout>"
yy424:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy425;
	default:	goto yy245;
	}
yy425:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy426;
	}
yy426:
#line 103 "yylex.re"
	{ RET(cast_sym_CHAR); }
#line 6328 "<stdout>"
yy427:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy428;
	default:	goto yy245;
	}
yy428:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy429;
	}
yy429:
#line 102 "yylex.re"
	{ RET(cast_sym_CASE); }
#line 6406 "<stdout>"
yy430:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy431;
	default:	goto yy245;
	}
yy431:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy432;
	default:	goto yy245;
	}
yy432:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'k':	goto yy433;
	default:	goto yy245;
	}
yy433:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy434;
	}
yy434:
#line 101 "yylex.re"
	{ RET(cast_sym_BREAK); }
#line 6496 "<stdout>"
yy435:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy436;
	default:	goto yy245;
	}
yy436:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy437;
	default:	goto yy245;
	}
yy437:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy244;
	default:	goto yy438;
	}
yy438:
#line 100 "yylex.re"
	{ RET(cast_sym_AUTO); }
#line 6580 "<stdout>"
yy439:
	++YYCURSOR;
#line 231 "yylex.re"
	{ RET(cast_sym_DIVEQ); }
#line 6585 "<stdout>"
yy441:
	++YYCURSOR;
#line 98 "yylex.re"
	{ goto comment2; }
#line 6590 "<stdout>"
yy443:
	++YYCURSOR;
#line 97 "yylex.re"
	{ goto comment; }
#line 6595 "<stdout>"
}
#line 296 "yylex.re"


 comment:
  
#line 6602 "<stdout>"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy451;
	case '\n':	goto yy449;
	case '*':	goto yy447;
	default:	goto yy453;
	}
yy447:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '/':	goto yy454;
	default:	goto yy448;
	}
yy448:
#line 315 "yylex.re"
	{ goto comment; }
#line 6622 "<stdout>"
yy449:
	++YYCURSOR;
#line 302 "yylex.re"
	{
            p->tok = p->pos = cursor; ++p->lineno;
            goto comment;
        }
#line 6630 "<stdout>"
yy451:
	++YYCURSOR;
#line 308 "yylex.re"
	{
            if (cursor == p->eof)
              rb_raise(cast_eParseError,
                       "%ld: unclosed multiline comment",
                       p->lineno);
        }
#line 6640 "<stdout>"
yy453:
	yych = *++YYCURSOR;
	goto yy448;
yy454:
	++YYCURSOR;
#line 300 "yylex.re"
	{ goto std; }
#line 6648 "<stdout>"
}
#line 316 "yylex.re"


 comment2:
  
#line 6655 "<stdout>"
{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy460;
	case '\n':	goto yy458;
	default:	goto yy462;
	}
yy458:
	++YYCURSOR;
#line 321 "yylex.re"
	{
            p->tok = p->pos = cursor; ++p->lineno;
            goto std;
        }
#line 6672 "<stdout>"
yy460:
	++YYCURSOR;
#line 327 "yylex.re"
	{
            if (cursor == p->eof) RET(Qnil);
            goto std;
        }
#line 6680 "<stdout>"
yy462:
	++YYCURSOR;
#line 332 "yylex.re"
	{ goto comment2; }
#line 6685 "<stdout>"
}
#line 333 "yylex.re"

}
